import keyMirror from 'keymirror';

export default keyMirror({
  GET_PROJECT_COMPLETED: null,
  CREATE_PROJECT_COMPLETED: null,
  DELETE_PROJECT_COMPLETED: null,
  UPDATE_PROJECT_COMPLETED: null,
  GET_ACTIVE_PROJECT_PARTS_COMPLETED: null,
  SET_ACTIVE_PROJECT_COMPLETED: null,
  SET_ACTIVE_PROJECT_VALUES_COMPLETED: null,
  SET_ADD_PART_VALUES_COMPLETED: null,
  ADD_PART_COMPLETED: null,
  SET_RENAME_PART_COMPLETED: null,
  SET_RENAME_PART_VALUE_COMPLETED: null,
  RENAME_PART_COMPLETED: null,
  SET_DELETE_PART_COMPLETED: null,
  DELETE_PART_COMPLETED: null,
  SET_DELETE_PROJECT_COMPLETED: null,
  RECEIVED_REPLICATION_DATA: null,
  UPDATE_TOKEN_REQUEST_EMAIL_COMPLETED: null,

  OPEN_DELETE_PROJECT_DIALOG: null,
  CLOSE_DELETE_PROJECT_DIALOG: null,

  OPEN_PROJECT_DIALOG: null,
  CLOSE_PROJECT_DIALOG: null,

  OPEN_REQUEST_TOKEN_DIALOG: null,
  CLOSE_REQUEST_TOKEN_DIALOG: null,

  OPEN_REQUEST_TOKEN_INDICATOR: null,
  CLOSE_REQUEST_TOKEN_INDICATOR: null,

  OPEN_DELETE_PART_DIALOG: null,
  CLOSE_DELETE_PART_DIALOG: null,

  OPEN_RENAME_PART_DIALOG: null,
  CLOSE_RENAME_PART_DIALOG: null,

  OPEN_ADD_PART_DIALOG: null,
  CLOSE_ADD_PART_DIALOG: null
});
