import keyMirror from 'keymirror';

export default keyMirror({
  GET_COMPLETED: null,
  CREATE_COMPLETED: null,
  DELETE_COMPLETED: null,
  UPDATE_COMPLETED: null,
  GET_ACTIVE_PROJECT_PARTS_COMPLETED: null,
  SET_ACTIVE_PROJECT_COMPLETED: null,
  SET_ACTIVE_PROJECT_VALUES_COMPLETED: null,
  SET_ADD_PART_VALUES_COMPLETED: null,
  ADD_PART_COMPLETED: null,
  SET_RENAME_PART_COMPLETED: null,
  SET_RENAME_PART_VALUE_COMPLETED: null,
  RENAME_PART_COMPLETED: null,
  SET_DELETE_PART_COMPLETED: null,
  DELETE_PART_COMPLETED: null,
  SET_DELETE_PROJECT_COMPLETED: null,
  DELETE_PROJECT_COMPLETED: null,
  RECEIVED_REPLICATION_DATA: null
});
